### ISSUE TITLE
Imitation of sample sites

### ISSUE THREAD

**Issue by PeterYves** [PeterYves/cdp-html-task#1]
### Evaluation Items

- [x] header (key visual)
  - [x] To display the title and subtitle in the upper and lower center as shown in the image.
- [x] CONCEPT section
  - [x] The layout should be such that the text is on the left and the images are on the right.
  - [x] Text should be 60% wide, and images should be 35% wide.
- [x] MENU section
  - [x] Display sample_menu_bg.jpg as the background.
  - [x] Display the menu so that it stays in place even when scrolling, as shown in the image.
  - [x] Recommended menu
    - [x] The width of each menu image should be 55%.
    - [x] Each menu should be 49% wide.
  - [x] Coffee menu
    - [x] The width of each menu should be 49%.
    - [x] The width of each menu image must be 20%.
    - [x] The width of each menu item displaying the name and amount must be 80%.
    - [x] The margin of the frame must be 20px.
- [x] ACCESS section
  - [x] dt and dd elements must be side-by-side
  - [x] dt element must have a width of 80px
  - [x] The width of GoogleMap must be 100%.
- [x] footer
  - [x] The background color must be #251e19 and the text color must be white.
  - [x] The height of footer should be 75px.
  - [x] Menu list and logo must be aligned horizontally.
  - [x] Menu list and logo must be displayed in the center of footer.
  *   [x] The copyright should be displayed in the center of the footer.

**Comment by nklbigone** [comment]
nkl

**Comment by nklbigone** [comment]
## Evaluation Items
```
 ✅header (key visual)
 ✅To display the title and subtitle in the upper and lower center as shown in the image.
 ✅CONCEPT section
 ✅The layout should be such that the text is on the left and the images are on the right.
 ✅Text should be 60% wide, and images should be 35% wide.
 ✅MENU section
 ✅Display sample_menu_bg.jpg as the background.
 ✅Display the menu so that it stays in place even when scrolling, as shown in the image.
 ✅Recommended menu
 ✅ The width of each menu image should be 55%.
 ✅Each menu should be 49% wide.
 ✅Coffee menu
 ✅The width of each menu should be 49%.
 ✅The width of each menu image must be 20%.
 ✅The width of each menu item displaying the name and amount must be 80%.
 ✅The margin of the frame must be 20px.
 ✅ACCESS section
 ✅dt and dd elements must be side-by-side
 ✅dt element must have a width of 80px
 ✅The width of GoogleMap must be 100%.
 ✅footer
 ✅The background color must be #251e19 and the text color must be white.
 ✅The height of footer should be 75px.
 ✅Menu list and logo must be aligned horizontally.
 ✅Menu list and logo must be displayed in the center of footer.
 ✅The copyright should be displayed in the center of the footer.
